In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
# Data Loading Code Hidden Here
import pandas as pd
# Load data
melbourne_file_path = '/content/gdrive/MyDrive/Colab_Notebooks/Melbourne_housing.csv'
melbourne_data = pd.read_csv(melbourne_file_path, low_memory=False)

In [ ]:
melbourne_data

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Latitude,Longtitude,Regionname,Propertycount,ParkingArea,Price
0,Abbotsford,68 Studley St,2,h,SS,Jellis,3/9/2016,2.5,3067.0,2.0,...,126.0,inf,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0,Carport,NaN
1,Airport West,154 Halsey Rd,3,t,PI,Nelson,3/9/2016,13.5,3042.0,3.0,...,303.0,225,2016.0,Moonee Valley City Council,-37.71800,144.87800,Western Metropolitan,3464.0,Detached Garage,840000.0
2,Albert Park,105 Kerferd Rd,2,h,S,hockingstuart,3/9/2016,3.3,3206.0,2.0,...,120.0,82,1900.0,Port Phillip City Council,-37.84590,144.95550,Southern Metropolitan,3280.0,Attached Garage,1275000.0
3,Albert Park,85 Richardson St,2,h,S,Thomson,3/9/2016,3.3,3206.0,2.0,...,159.0,inf,NaN,Port Phillip City Council,-37.84500,144.95380,Southern Metropolitan,3280.0,Indoor,1455000.0
4,Alphington,30 Austin St,3,h,SN,McGrath,3/9/2016,6.4,3078.0,3.0,...,174.0,122,2003.0,Darebin City Council,-37.78180,145.01980,Northern Metropolitan,2211.0,Parkade,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Reservoir,18 Elinda Pl,3,u,SP,RW,30/09/2017,12.0,3073.0,3.0,...,NaN,105,1990.0,Darebin City Council,-37.69769,145.02332,Northern Metropolitan,21650.0,Parkade,475000.0
34853,Roxburgh Park,14 Stainsby Cr,4,h,S,Raine,30/09/2017,20.6,3064.0,4.0,...,NaN,225,1995.0,Hume City Council,-37.63665,144.92976,Northern Metropolitan,5833.0,Underground,591000.0
34854,Springvale South,8 Bellbird Ct,4,h,PI,Barry,30/09/2017,22.2,3172.0,4.0,...,534.0,152,1970.0,Greater Dandenong City Council,-37.97037,145.15449,South-Eastern Metropolitan,4054.0,Carport,NaN
34855,Springvale South,30 Waddington Cr,3,h,S,Harcourts,30/09/2017,22.2,3172.0,3.0,...,544.0,NaN,NaN,Greater Dandenong City Council,-37.97751,145.14813,South-Eastern Metropolitan,4054.0,Detached Garage,780500.0
34856,Westmeadows,42 Pascoe St,4,h,S,Barry,30/09/2017,16.5,3049.0,4.0,...,813.0,140,1960.0,Hume City Council,-37.67631,144.89409,Northern Metropolitan,2474.0,Attached Garage,791000.0

In [ ]:
# Filter rows with missing price values
filtered_melbourne_data = melbourne_data.dropna(axis=1)
# Choose target and features

In [ ]:
filtered_melbourne_data

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Regionname,ParkingArea
0,Abbotsford,68 Studley St,2,h,SS,Jellis,3/9/2016,Northern Metropolitan,Carport
1,Airport West,154 Halsey Rd,3,t,PI,Nelson,3/9/2016,Western Metropolitan,Detached Garage
2,Albert Park,105 Kerferd Rd,2,h,S,hockingstuart,3/9/2016,Southern Metropolitan,Attached Garage
3,Albert Park,85 Richardson St,2,h,S,Thomson,3/9/2016,Southern Metropolitan,Indoor
4,Alphington,30 Austin St,3,h,SN,McGrath,3/9/2016,Northern Metropolitan,Parkade
...,...,...,...,...,...,...,...,...,...
34852,Reservoir,18 Elinda Pl,3,u,SP,RW,30/09/2017,Northern Metropolitan,Parkade
34853,Roxburgh Park,14 Stainsby Cr,4,h,S,Raine,30/09/2017,Northern Metropolitan,Underground
34854,Springvale South,8 Bellbird Ct,4,h,PI,Barry,30/09/2017,South-Eastern Metropolitan,Carport
34855,Springvale South,30 Waddington Cr,3,h,S,Harcourts,30/09/2017,South-Eastern Metropolitan,Detached Garage
34856,Westmeadows,42 Pascoe St,4,h,S,Barry,30/09/2017,Northern Metropolitan,Attached Garage

In [ ]:
# Filter rows with missing price values
filtered_melbourne_data = melbourne_data.dropna()
# Choose target and features

In [ ]:
filtered_melbourne_data

,Suburb,Address,Rooms,Type,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Latitude,Longtitude,Regionname,Propertycount,ParkingArea,Price
1,Airport West,154 Halsey Rd,3,t,PI,Nelson,3/9/2016,13.5,3042.0,3.0,...,303.0,225,2016.0,Moonee Valley City Council,-37.71800,144.87800,Western Metropolitan,3464.0,Detached Garage,840000.0
2,Albert Park,105 Kerferd Rd,2,h,S,hockingstuart,3/9/2016,3.3,3206.0,2.0,...,120.0,82,1900.0,Port Phillip City Council,-37.84590,144.95550,Southern Metropolitan,3280.0,Attached Garage,1275000.0
5,Alphington,6 Smith St,4,h,S,Brace,3/9/2016,6.4,3078.0,3.0,...,853.0,263,1930.0,Darebin City Council,-37.77070,145.03180,Northern Metropolitan,2211.0,Underground,2000000.0
6,Alphington,5/6 Yarralea St,3,h,S,Jellis,3/9/2016,6.4,3078.0,3.0,...,208.0,inf,2013.0,Darebin City Council,-37.78540,145.03250,Northern Metropolitan,2211.0,Outdoor Stall,1110000.0
7,Altona,158 Queen St,3,h,VB,Greg,3/9/2016,13.8,3018.0,3.0,...,352.0,242,2015.0,Hobsons Bay City Council,-37.87000,144.82500,Western Metropolitan,5301.0,Parking Pad,520000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34838,Caroline Springs,29 Edgbaston Pde,3,h,SP,Crane,30/09/2017,14.8,3023.0,3.0,...,355.0,154,2003.0,Melton City Council,-37.73978,144.72851,Western Metropolitan,7719.0,Outdoor Stall,560000.0
34846,Keysborough,3 Cobain St,3,h,S,Area,30/09/2017,25.2,3173.0,3.0,...,539.0,126,1969.0,Greater Dandenong City Council,-37.98916,145.17233,South-Eastern Metropolitan,8459.0,Outdoor Stall,771000.0
34848,Maidstone,15 Ballarat Rd,2,h,SP,Biggin,30/09/2017,6.4,3012.0,2.0,...,300.0,108,1950.0,Maribyrnong City Council,-37.78842,144.88218,Western Metropolitan,3873.0,Carport,611500.0
34851,Noble Park,5 Blaby St,3,h,PI,C21,30/09/2017,22.7,3174.0,3.0,...,569.0,130,1959.0,Greater Dandenong City Council,-37.96900,145.18226,South-Eastern Metropolitan,11806.0,Indoor,627500.0
34856,Westmeadows,42 Pascoe St,4,h,S,Barry,30/09/2017,16.5,3049.0,4.0,...,813.0,140,1960.0,Hume City Council,-37.67631,144.89409,Northern Metropolitan,2474.0,Attached Garage,791000.0

In [ ]:
print(filtered_melbourne_data.columns)

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Method', 'SellerG', 'Date',
       'Distance', 'Postcode', 'Bedroom', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'YearBuilt', 'CouncilArea', 'Latitude', 'Longtitude',
       'Regionname', 'Propertycount', 'ParkingArea', 'Price'],
      dtype='object')

In [ ]:
y = filtered_melbourne_data.Price
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Latitude', 'Longtitude']
X = filtered_melbourne_data[melbourne_features]

In [ ]:
y

1         840000.0
2        1275000.0
5        2000000.0
6        1110000.0
7         520000.0
           ...
34838     560000.0
34846     771000.0
34848     611500.0
34851     627500.0
34856     791000.0
Name: Price, Length: 8890, dtype: float64

In [ ]:
X

       Rooms  Bathroom  Landsize  Latitude  Longtitude
1          3       2.0     303.0 -37.71800   144.87800
2          2       1.0     120.0 -37.84590   144.95550
5          4       2.0     853.0 -37.77070   145.03180
6          3       2.0     208.0 -37.78540   145.03250
7          3       2.0     352.0 -37.87000   144.82500
...      ...       ...       ...       ...         ...
34838      3       2.0     355.0 -37.73978   144.72851
34846      3       1.0     539.0 -37.98916   145.17233
34848      2       1.0     300.0 -37.78842   144.88218
34851      3       1.0     569.0 -37.96900   145.18226
34856      4       2.0     813.0 -37.67631   144.89409

[8890 rows x 5 columns]

In [ ]:
melbourne_data.Date

0          3/9/2016
1          3/9/2016
2          3/9/2016
3          3/9/2016
4          3/9/2016
            ...
34852    30/09/2017
34853    30/09/2017
34854    30/09/2017
34855    30/09/2017
34856    30/09/2017
Name: Date, Length: 34857, dtype: object

In [ ]:
melbourne_data.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom          float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea      object
YearBuilt        float64
CouncilArea       object
Latitude         float64
Longtitude       float64
Regionname        object
Propertycount    float64
ParkingArea       object
Price            float64
dtype: object

In [ ]:
from sklearn.tree import DecisionTreeRegressor
# Define model
# 10, 50 ,100, 500, 1000
melbourne_model = DecisionTreeRegressor()

# Fit model
melbourne_model.fit(X, y)

DecisionTreeRegressor()

In [ ]:
yp=melbourne_model.predict(X)

Once we have a model, here is how we calculate the mean absolute error:

In [ ]:
yp = melbourne_model.predict(X)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y, yp)

896.9816272965878

In [ ]:
y.mean()

np.float64(1092841.1446569178)

In [ ]:
(mean_absolute_error(y, yp)/y.mean())*100

np.float64(0.08207795173910501)

In [ ]:
from sklearn.model_selection import train_test_split
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

forest_model = RandomForestRegressor(n_estimators=1000,max_leaf_nodes=500,random_state=1)
forest_model.fit(train_X, train_y)
melb_preds = forest_model.predict(val_X)
print(mean_absolute_error(val_y, melb_preds))

184364.2340650345

In [ ]:
(mean_absolute_error(val_y, melb_preds)/y.mean())*100

np.float64(16.87017687487536)